spring.application.name=Eduqualis

# Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/app_db
spring.datasource.username=jmfs
spring.datasource.password=jmfs
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Upload de Arquivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Configuração de Log
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.file.name=app.log

eduqualis.video.dir=/home/joao/Documents/intellij/social/videos/
eduqualis.photo.dir=/home/joao/Documents/intellij/social/photos/